Milestone 1 - Project Setup
epinczinger/TicTacToe pull request #1
Opened 2020-07-13 18:06 UTC by gdumani

This project is about the development of a simple TicTacToe game using Ruby.
In this Milestone the following objectives were achieved:

- Lib and bin directories were created
- main.rb file was added to the bin directory to start the project there.

2020-07-13 20:28 UTC, rammazzoti2000 requested changes
### Hello team 🙌, I am Alex your code reviewer for this project
Great job team this far, congrats on the `Readme` file, even though it was not yet requested a readme file, yours is already great 💪 , also the PR summary is descriptive and overall the repo looks professional.
There is just on small thing to adjust before approving this project, checkout the comments bellow 👇 
## 🛑 Required Changes 🚧 👷 
- [x] The `GitHub Actions` configuration is not complete, you are missing the first step, please check again [the official repo](https://github.com/microverseinc/linters-config/tree/master/ruby) and make sure you have your [`.github/workflows/linters.yml`](https://github.com/microverseinc/linters-config/blob/master/ruby/.github/workflows/linters.yml) file configured as well
![image](https://user-images.githubusercontent.com/3244654/87349649-f1a1e600-c556-11ea-8472-513bd7f4f9c6.png)
- [x] Also the first line in the executable main file must be `#!/usr/bin/env ruby` followed by the `
puts "Hello world"` statement in the second line
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of **_alexandru_** if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-07-13 20:28 UTC, rammazzoti2000 commented on bin/main.rb
> +puts "Hello World"
On line 1 it should be `#!/usr/bin/env ruby` for the executable main file, followed on line 2 by `puts "Hello World"`

2020-07-13 21:22 UTC, epinczinger commented
- Added linters.yml and fixed rubocop errors.
-First-line on main.rb has been added.

2020-07-14 00:10 UTC, lekegitrepo commented
### Good job :+1: Team.
#### This project is approved, go ahead and merge the branch now.

#### _Reviewed by Temitayo Adeleke_.

2020-07-14 00:10 UTC, lekegitrepo approved these changes
#### Status: Approve

2020-07-14 00:22 UTC, merged